{"tests": [{"data": {"inputs": {"files|type": "many", "files|options|option": "no", "files_failed": false, "files|many_files": {"src": "hda", "id": "2891970512fa2d5a"}, "fasta_out": true}, "job": {"inputs": {"many_files": {"src": "hda", "id": "2891970512fa2d5a", "uuid": "1e323901-9c3f-4b9b-b8f8-6eb074a740d0"}}, "update_time": "2016-12-16T09:13:00.751139", "tool_id": "blastalign", "outputs": {"outfile": {"src": "hda", "id": "5729865256bc2525", "uuid": "402b5399-baaf-4a4a-a9a3-fb4651d2e1ae"}, "nxs_zip": {"src": "hda", "id": "8155e4b4bf1581ff", "uuid": "ab313023-3d4c-4483-b21e-38cd869816e3"}, "fasta_zip": {"src": "hda", "id": "7b55dbb89df8f4e5", "uuid": "38f59327-cd96-4c3d-a5e4-ccb2c2cfb8b1"}, "phy_zip": {"src": "hda", "id": "54f2a3a23292eb07", "uuid": "18c471a2-65f3-4af7-86cc-5e0a91619a31"}}, "stdout": "", "command_line": "python /home/umr7144/abice/vmataigne/Documents/AdaptSearch/adaptsearch-master/galaxy_wrappers/04_BlastAlign/24_prepare_BlastAlignRuns.py /tmp/tmpCinkIO/files/000/dataset_1.dat oui 95 F >/tmp/tmpCinkIO/files/000/dataset_2.dat;", "exit_code": 0, "state": "error", "create_time": "2016-12-16T09:12:49.366097", "params": {"files": "{\"type\": \"many\", \"options\": {\"option\": \"no\", \"__current_case__\": 1}, \"__current_case__\": 1, \"many_files\": {\"values\": [{\"src\": \"hda\", \"id\": \"2891970512fa2d5a\"}]}}", "files_failed": "\"false\"", "chromInfo": "\"/tmp/tmpCinkIO/galaxy-dev/tool-data/shared/ucsc/chrom/hg17.len\"", "dbkey": "\"hg17\"", "fasta_out": "\"true\""}, "stderr": "sh: 1: /home/umr7144/abice/vmataigne/Documents/AdaptSearch/adaptsearch-master/galaxy_wrappers/04_BlastAlign/BlastAlign: not found\nTraceback (most recent call last):\n  File \"/home/umr7144/abice/vmataigne/Documents/AdaptSearch/adaptsearch-master/galaxy_wrappers/04_BlastAlign/phylip2fasta.py\", line 17, in <module>\n    F1 = open(\"%s\" %f1, 'r')\nIOError: [Errno 2] No such file or directory: './locus1_sp2.fasta.phy'\nmv: impossible d'\u00e9valuer \u00ab./locus1_sp2.fasta.fasta\u00bb: Aucun fichier ou dossier de ce type\nsh: 1: /home/umr7144/abice/vmataigne/Documents/AdaptSearch/adaptsearch-master/galaxy_wrappers/04_BlastAlign/BlastAlign: not found\nTraceback (most recent call last):\n  File \"/home/umr7144/abice/vmataigne/Documents/AdaptSearch/adaptsearch-master/galaxy_wrappers/04_BlastAlign/phylip2fasta.py\", line 17, in <module>\n    F1 = open(\"%s\" %f1, 'r')\nIOError: [Errno 2] No such file or directory: './locus2_sp2.fasta.phy'\nmv: impossible d'\u00e9valuer \u00ab./locus2_sp2.fasta.fasta\u00bb: Aucun fichier ou dossier de ce type\nsh: 1: /home/umr7144/abice/vmataigne/Documents/AdaptSearch/adaptsearch-master/galaxy_wrappers/04_BlastAlign/BlastAlign: not found\nTraceback (most recent call last):\n  File \"/home/umr7144/abice/vmataigne/Documents/AdaptSearch/adaptsearch-master/galaxy_wrappers/04_BlastAlign/phylip2fasta.py\", line 17, in <module>\n    F1 = open(\"%s\" %f1, 'r')\nIOError: [Errno 2] No such file or directory: './locus3_sp2.fasta.phy'\nmv: impossible d'\u00e9valuer \u00ab./locus3_sp2.fasta.fasta\u00bb: Aucun fichier ou dossier de ce type\nsh: 1: /home/umr7144/abice/vmataigne/Documents/AdaptSearch/adaptsearch-master/galaxy_wrappers/04_BlastAlign/BlastAlign: not found\nTraceback (most recent call last):\n  File \"/home/umr7144/abice/vmataigne/Documents/AdaptSearch/adaptsearch-master/galaxy_wrappers/04_BlastAlign/phylip2fasta.py\", line 17, in <module>\n    F1 = open(\"%s\" %f1, 'r')\nIOError: [Errno 2] No such file or directory: './locus4_sp2.fasta.phy'\nmv: impossible d'\u00e9valuer \u00ab./locus4_sp2.fasta.fasta\u00bb: Aucun fichier ou dossier de ce type\nsh: 1: /home/umr7144/abice/vmataigne/Documents/AdaptSearch/adaptsearch-master/galaxy_wrappers/04_BlastAlign/BlastAlign: not found\nTraceback (most recent call last):\n  File \"/home/umr7144/abice/vmataigne/Documents/AdaptSearch/adaptsearch-master/galaxy_wrappers/04_BlastAlign/phylip2fasta.py\", line 17, in <module>\n    F1 = open(\"%s\" %f1, 'r')\nIOError: [Errno 2] No such file or directory: './locus5_sp2.fasta.phy'\nmv: impossible d'\u00e9valuer \u00ab./locus5_sp2.fasta.fasta\u00bb: Aucun fichier ou dossier de ce type\nsh: 1: /home/umr7144/abice/vmataigne/Documents/AdaptSearch/adaptsearch-master/galaxy_wrappers/04_BlastAlign/BlastAlign: not found\nTraceback (most recent call last):\n  File \"/home/umr7144/abice/vmataigne/Documents/AdaptSearch/adaptsearch-master/galaxy_wrappers/04_BlastAlign/phylip2fasta.py\", line 17, in <module>\n    F1 = open(\"%s\" %f1, 'r')\nIOError: [Errno 2] No such file or directory: './locus6_sp2.fasta.phy'\nmv: impossible d'\u00e9valuer \u00ab./locus6_sp2.fasta.fasta\u00bb: Aucun fichier ou dossier de ce type\nsh: 1: /home/umr7144/abice/vmataigne/Documents/AdaptSearch/adaptsearch-master/galaxy_wrappers/04_BlastAlign/BlastAlign: not found\nTraceback (most recent call last):\n  File \"/home/umr7144/abice/vmataigne/Documents/AdaptSearch/adaptsearch-master/galaxy_wrappers/04_BlastAlign/phylip2fasta.py\", line 17, in <module>\n    F1 = open(\"%s\" %f1, 'r')\nIOError: [Errno 2] No such file or directory: './locus7_sp2.fasta.phy'\nmv: impossible d'\u00e9valuer \u00ab./locus7_sp2.fasta.fasta\u00bb: Aucun fichier ou dossier de ce type\nsh: 1: /home/umr7144/abice/vmataigne/Documents/AdaptSearch/adaptsearch-master/galaxy_wrappers/04_BlastAlign/BlastAlign: not found\nTraceback (most recent call last):\n  File \"/home/umr7144/abice/vmataigne/Documents/AdaptSearch/adaptsearch-master/galaxy_wrappers/04_BlastAlign/phylip2fasta.py\", line 17, in <module>\n    F1 = open(\"%s\" %f1, 'r')\nIOError: [Errno 2] No such file or directory: './locus8_sp2.fasta.phy'\nmv: impossible d'\u00e9valuer \u00ab./locus8_sp2.fasta.fasta\u00bb: Aucun fichier ou dossier de ce type\nsh: 1: /home/umr7144/abice/vmataigne/Documents/AdaptSearch/adaptsearch-master/galaxy_wrappers/04_BlastAlign/BlastAlign: not found\nTraceback (most recent call last):\n  File \"/home/umr7144/abice/vmataigne/Documents/AdaptSearch/adaptsearch-master/galaxy_wrappers/04_BlastAlign/phylip2fasta.py\", line 17, in <module>\n    F1 = open(\"%s\" %f1, 'r')\nIOError: [Errno 2] No such file or directory: './locus9_sp2.fasta.phy'\nmv: impossible d'\u00e9valuer \u00ab./locus9_sp2.fasta.fasta\u00bb: Aucun fichier ou dossier de ce type\nsh: 1: /home/umr7144/abice/vmataigne/Documents/AdaptSearch/adaptsearch-master/galaxy_wrappers/04_BlastAlign/BlastAlign: not found\nTraceback (most recent call last):\n  File \"/home/umr7144/abice/vmataigne/Documents/AdaptSearch/adaptsearch-master/galaxy_wrappers/04_BlastAlign/phylip2fasta.py\", line 17, in <module>\n    F1 = open(\"%s\" %f1, 'r')\nIOError: [Errno 2] No such file or directory: './locus10_sp2.fasta.phy'\nmv: impossible d'\u00e9valuer \u00ab./locus10_sp2.fasta.fasta\u00bb: Aucun fichier ou dossier de ce type\nsh: 1: /home/umr7144/abice/vmataigne/Documents/AdaptSearch/adaptsearch-master/galaxy_wrappers/04_BlastAlign/BlastAlign: not found\nTraceback (most recent call last):\n  File \"/home/umr7144/abice/vmataigne/Documents/AdaptSearch/adaptsearch-master/galaxy_wrappers/04_BlastAlign/phylip2fasta.py\", line 17, in <module>\n    F1 = open(\"%s\" %f1, 'r')\nIOError: [Errno 2] No such file or directory: './locus1_sp3.fasta.phy'\nmv: impossible d'\u00e9valuer \u00ab./locus1_sp3.fasta.fasta\u00bb: Aucun fichier ou dossier de ce type\n", "job_metrics": [], "model_class": "Job", "external_id": "5485", "id": "5729865256bc2525", "user_email": "test@bx.psu.edu"}, "output_problems": ["Job in error state.", "Job in error state."]}, "id": "functional.test_toolbox.TestForTool_blastalign.test_tool_000000", "has_data": true}, {"data": null, "id": "functional.test_toolbox.TestForTool_blastalign.test_tool_000000", "has_data": false}], "version": "0.1", "exit_code": 1, "summary": {"num_skips": 0, "num_errors": 1, "num_failures": 1, "num_tests": 2}}